#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

OPTS="-q"

# Turn Numlock on for the TTYs, needed for cryptsetup (when user want's to use numbers):
if [ -x /usr/sbin/laptop-detect ] ; then
    # only if we are not in laptop
    if ! /usr/sbin/laptop-detect ; then

        if [ -x /usr/bin/setleds ]; then
            for tty in /dev/tty[1-6]; do
                /usr/bin/setleds -D +num < $tty
            done
        fi
    fi
fi

